### ISSUE TITLE
EMBL import——zlib.error: Error -3 while decompressing data:invalid distance code

### ISSUE THREAD

**Issue by asPinus2050** [metabaRfactory/metabaR#53]
Hi!  Celine Mercier
       Recently, STD_INV_13.dat.gz was downloaded from the EMBL database. When I try to import STD_INV_13.dat.gz from the Wolf tutorial to Build a reference database,  either on Mac Terminal or Linux system, I get the following error:

(obi3-env)@ [aspinus]$ obi import --embl EMBL coi_embl2023/embl_refs
2023-03-21 09:22:05,456 [import : INFO ]  obi import: imports an object (file(s), obiview, taxonomy...) into a DMS
2023-03-21 09:22:05,471 [import : INFO ]  Importing an unknown number of entries
Parsing file EMBL/STD_INV_11.dat.gz (1/13)
2023-03-21 09:22:07,994 [import : INFO ]  Imported 0 entries
2023-03-21 09:22:16,768 [import : INFO ]  Imported 50000 entries
…………
…………
…………

Parsing file EMBL/STD_INV_13.dat.gz (13/13)
2023-03-21 13:06:30,239 [import : INFO ]  Imported 12250000 entries
2023-03-21 13:06:52,489 [import : INFO ]  Imported 12300000 entries
Traceback (most recent call last):
  File "/data/home/obitools3/obi3-env/bin/obi", line 4, in <module>
    __import__('pkg_resources').run_script('OBITools3==3.0.1b21', 'obi')
  File "/data/home/obitools3/obi3-env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/data/home/obitools3/obi3-env/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1462, in run_script
    exec(code, namespace, namespace)
  File "/data/home/obitools3/obi3-env/lib/python3.8/site-packages/OBITools3-3.0.1b21-py3.8-linux-x86_64.egg/EGG-INFO/scripts/obi", line 62, in <module>
    config[root_config_name]['module'].run(config)
  File "python/obitools3/commands/import.pyx", line 333, in obitools3.commands.import.run
  File "python/obitools3/parsers/embl.pyx", line 186, in emblIterator_dir
  File "python/obitools3/parsers/embl.pyx", line 143, in emblIterator_file
  File "python/obitools3/files/linebuffer.pyx", line 22, in __iter__
  File "/usr/local/lib/python3.8/gzip.py", line 384, in readline
    return self._buffer.readline(size)
  File "/usr/local/lib/python3.8/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/usr/local/lib/python3.8/gzip.py", line 481, in read
    uncompress = self._decompressor.decompress(buf, size)
zlib.error: Error -3 while decompressing data: invalid distance code   

Any advice given would be greatly appreciated and thanks for your work on OBITools!   Aspinus

**Comment by celine-mercier** [comment]
Hello,
The right place for OBITools3 issues is here: https://git.metabarcoding.org/obitools/obitools3/-/issues/
It looks like that file is corrupted, can you try downloading it again?
Cheers
Celine
